version: "3.2"

services:
  dev:
    container_name: node-template
    image: paritytech/ci-linux:974ba3ac-20201006
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/node-ibchaindev --dev --ws-external"
  ibdev:
    build: .
    container_name: node-ibdevchain
    image: node-ibdevchain:1
    ports:
      - "9944:9944"
    volumes:
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "/var/www/node-ibchaindev --dev --ws-external"
  purge-ibdev:
    container_name: node-ibdevchain
    image: node-ibdevchain:1
    volumes:
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "/var/www/node-ibchaindev purge-chain --dev -y"
